name: bosonic-gates
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.26.4
  - scipy=1.12.0
  - matplotlib=3.8.3
  - ipywidgets=8.1.2
  - jupyterlab=4.1.5
  - ipympl=0.9.3
  - sympy=1.12
  - pip
  - pip:
      - qutip==5.0.4
      - qutip-jax==0.0.5
      - jax[cpu]==0.4.26
      - optax==0.2.2
